name: Refresh Stale Issues with Help Wanted Label
on:
  schedule:
  - cron: "0 0 15 * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/stale@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'Please comment if you are still working on this issue, as it has been inactive for 90 days. To give everyone a chance to contribute, we are releasing it to new contributors.'
        stale-issue-label: 'help wanted'
        exempt-issue-labels: 'help wanted,blocked'
        stale-pr-message: 'Please comment if you are still working on this PR, as it has been inactive for 90 days. To give everyone a chance to contribute, we are releasing it for new contributors to take over.'
        stale-pr-label: 'help wanted'
        exempt-pr-labels: 'help wanted,blocked'
        remove-stale-when-updated: false
        days-before-stale: 90
        days-before-close: -1
